In [1]:
import numpy as np
import time

print('Input number.')
count = input()
if count is None or count == '':
    count = 10
for i in range(int(count)):
    a = np.array([1,2,3,4,5,6,7,8,9,10,
                  11,12,13,14,15,16,17,18,20,
                  21,22,23,24,25,26,27,28,29,30,
                  31,32,33,34,35,36])
    num_list = np.random.choice(a, 6,replace=False)
    print(num_list)

#time.sleep(3600)

Input number.


[17  6 18 14  3 34]
[32  8 14 21 33  6]
[24 31  8 30  1  9]
[11 20 36  6 23 33]
[23 21 24 18 22 17]
[26  7 36 15 29 24]
[21 13  8  5 14 20]
[30 16  3 22 25  5]
[16  9 22 14 28 23]
[30 11 28  9 16 34]
